

title: 'CTRLALTDAN'
tagline: 'My Code'
description: ''
url: https://www.ctrlaltdan.com
baseurl: /
  
permalink: pretty

author:
  name: 'Dan Warner'
  url: https://ctrlaltdan.com/

paginate: 20

github:
  repo: https://github.com/dubs999

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
